#!/bin/bash

commit=$1
parent=$2
child=$3

git checkout -b temp
git branch -f temp parent
git commit -m "Recommitting ${commit} between ${parent} and ${child}"

git checkout main
git rebase temp
git branch -d temp
