#!/bin/bash

parent=$1

# first we create a new branch, move it to parent commit
git branch temp
git branch -f temp ${parent}
git checkout temp

# do some dummy changes and commit
cd ..
mkdir Temp
cd Temp
touch hello
git add .

git commit -m "Commit after ${parent}"

# come back to the now diverged main branch and rebase it with 
# temp branch
git checkout main
cd ..
git rebase temp

# work over, delete temp
git branch -D temp
